on:
  push:
    branches:
      - master
jobs:
  build-gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish gem
        uses: jstastny/publish-gem-to-github@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: grnhse
